name: nordangler
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  animations: ^2.0.11
  cached_network_image: ^3.2.3
  toasty_box: ^1.0.1

  
  curved_navigation_bar: ^1.0.3

  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+2
  flutter_launcher_icons: ^0.13.1

  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.0
  page_transition: ^2.1.0
  share_files_and_screenshot_widgets: ^1.0.6
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  provider: ^6.1.1
  flutter_splash_screen: ^2.0.1+1
  carousel_slider: ^4.2.1
  firebase_analytics: ^10.8.6
  firebase_messaging: ^14.7.16
  firebase_core: ^2.25.4
  animated_text_kit: ^4.2.2
  firebase_app_check: ^0.2.1+14

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/animation/
    - assets/images/animation/audio/sample.mp4/


