// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZArjzVaOCJw4pY1TJU5gPlD2-8-vDpdE',
    appId: '1:219082891653:web:68c6baee5bfc202d7724ec',
    messagingSenderId: '219082891653',
    projectId: 'new-nord-angler-app',
    authDomain: 'new-nord-angler-app.firebaseapp.com',
    storageBucket: 'new-nord-angler-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTv3LWtBq55_STb8VAfnTT4cvMpDslNV0',
    appId: '1:219082891653:android:5d7a10d5dd1398ec7724ec',
    messagingSenderId: '219082891653',
    projectId: 'new-nord-angler-app',
    storageBucket: 'new-nord-angler-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkrCGr-PJdyIWY_aD09a6zqvkZTG_lgm4',
    appId: '1:219082891653:ios:a93c38ba77be9efd7724ec',
    messagingSenderId: '219082891653',
    projectId: 'new-nord-angler-app',
    storageBucket: 'new-nord-angler-app.appspot.com',
    iosBundleId: 'com.example.nordangler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkrCGr-PJdyIWY_aD09a6zqvkZTG_lgm4',
    appId: '1:219082891653:ios:2a8319a8306087627724ec',
    messagingSenderId: '219082891653',
    projectId: 'new-nord-angler-app',
    storageBucket: 'new-nord-angler-app.appspot.com',
    iosBundleId: 'com.example.nordangler.RunnerTests',
  );
}
